trigger:
- main

variables:
- group: bootstrap-variables-kv
- name: AZURE_DEVOPS_EXT_GITHUB_PAT

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - bash: az --version
    displayName: 'Show Azure CLI version'

  - bash: echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
    env:
      AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)
    displayName: 'Login Azure DevOps Extension'

  - bash: az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject) --use-git-aliases true
    displayName: 'Set default Azure DevOps organization and project'
    
  # - bash:
  #     az devops project create --name 'TestProject1'
  #   displayName: 'Create a new project'

  # - bash:
  #     # export AZURE_DEVOPS_EXT_GITHUB_PAT= $(github-pat-token)
  #     az pipelines variable create --name 'AZURE_DEVOPS_EXT_GITHUB_PAT' --value $(github-pat-token) --secret true
  #   displayName: 'Set PAT'

  - bash: echo '##vso[task.setvariable variable=AZURE_DEVOPS_EXT_GITHUB_PAT]$(github-pat-token)'
    displayName: Set new variable value

  - bash:
      # az pipelines variable list
      # echo $AZURE_DEVOPS_EXT_GITHUB_PAT
      # echo "From variable:"
      # echo $github-pat-token
      # az pipelines variable update --name 'AZURE_DEVOPS_EXT_GITHUB_PAT' --value $github-pat-token --secret true
      # echo $AZURE_DEVOPS_EXT_GITHUB_PAT      
      az devops service-endpoint github create --github-url 'https://github.com/ai-factory-azure' --name 'Github-AI-Factory' --org 'https://dev.azure.com/ai-factory-azure' --project 'TestProject1'
      # az devops service-endpoint update --id $DOCKER_CONNECTION_ID --enable-for-all
      # az devops service-endpoint update --id --enable-for-all true      
    displayName: 'Create Github Service Endpoint'

  - bash:
      echo $GITHUB_CONNECTION_ID
    #  az devops service-endpoint update --id $GITHUB_CONNECTION_ID --enable-for-all
    displayName: 'Update endpoint'