trigger:
- main

variables:
- group: bootstrap-variables

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - bash: az --version
    displayName: 'Show Azure CLI version'

  - bash: echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
    env:
      AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)
    displayName: 'Login Azure DevOps Extension'

  - bash: az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject) --use-git-aliases true
    displayName: 'Set default Azure DevOps organization and project'
    
  # - bash:
  #     az devops project create --name 'TestProject2'
  #   displayName: 'Create a new project'

  - bash:
      az pipelines variable list
      echo $AZURE_DEVOPS_EXT_GITHUB_PAT
      echo "From variable:"
      echo $github-pat-token
      az pipelines variable update --name 'AZURE_DEVOPS_EXT_GITHUB_PAT' --value $github-pat-token --secret true
      echo $AZURE_DEVOPS_EXT_GITHUB_PAT
      az devops service-endpoint github create --github-url 'https://github.com/ai-factory-azure/iac-arm'--name 'Github-IAC' --org 'https://dev.azure.com/ai-factory-azure' --project 'TestProject1'
    displayName: 'Create Github Service Endpoint'