trigger:
- azure-devops-setup

variables:
- group: bootstrap-variables-kv
- template: project-variables.yml

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - bash: az --version
    displayName: 'Show Azure CLI version'

  - bash: echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
    env:
      AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)
    displayName: 'Login Azure DevOps Extension'
  
  - bash:
      az devops project create --name $(PROJECT-NAME)
    continueOnError: true    
    displayName: 'Create a new project'

  - bash: az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(PROJECT-NAME) --use-git-aliases true
    displayName: 'Set default Azure DevOps organization and project'

  - bash: 
      echo '##vso[task.setvariable variable=AZURE_DEVOPS_EXT_GITHUB_PAT]$(AZURE-DEVOPS-EXT-GITHUB-PAT)'
    displayName: Set Github PAT variable value

  - bash: 
      echo '##vso[task.setvariable variable=AZURE_DEVOPS_EXT_AZURE_RM_SERVICE_PRINCIPAL_KEY]$(AZURE-RM-SERVICE-PRINCIPAL-KEY-DEV)'
    displayName: Set Azure Service Principal value

  - bash: 
      az devops service-endpoint github create  --github-url $(GITHUB-ORG-URL) 
                                                --name $(GITHUB-SERVICE-ENDPOINT_NAME) 
                                                --org $(System.TeamFoundationCollectionUri)
                                                --project $(PROJECT-NAME)
      # az devops service-endpoint update --id $GITHUB_CONNECTION_ID --enable-for-all
      # az devops service-endpoint update --id --enable-for-all true      
    displayName: 'Create Github Service Endpoint'
  
  - bash:
      az devops service-endpoint update --id $(az devops service-endpoint list --organization https://dev.azure.com/ai-factory-azure --project 'testproject100' -o table |grep Github-Service-Endpoint|cut -d" " -f1) --enable-for-all --organization https://dev.azure.com/ai-factory-azure --project 'testproject100'
    displayName: 'Update Service Endpoint'

  # - bash:
  #     az devops service-endpoint azurerm create --azure-rm-service-principal-id $(AZURE-RM-SERVICE-PRINCIPAL-ID-DEV)
  #                                         --azure-rm-subscription-id $(AZURE-RM-SUBSCRIPTION-ID-DEV)
  #                                         --azure-rm-subscription-name 'Microsoft Azure Internal Consumption -MK'
  #                                         --azure-rm-tenant-id $(AZURE-RM-TENANT-ID)
  #                                         --name AZURE-SERVICE-ENDPOINT-NAME
  #                                         --org $(System.TeamFoundationCollectionUri) 
  #                                         --project $(PROJECT-NAME)
  #   displayName: 'Create Azure Service Connection'

  # - bash:
  #     az devops service-endpoint update --id $GITHUB_CONNECTION_ID --enable-for-all --debug
  #   displayName: 'Update endpoint'

  # - bash:
  #     az pipelines create --name $(IAC-PIPELINE-NAME)
  #                         --description 'Pipeline for MNIST Project'
  #                         --repository $(IAC-REPOSITORY-URL)
  #                         --branch $(IAC-BRANCH)
  #                         --yml-path $(IAC-YML-PATH)
  #                         --service-connection $(az devops service-endpoint list --organization https://dev.azure.com/ai-factory-azure --project 'testproject1' -o table |grep Github-AI-Factory13|cut -d" " -f1)
  #                         --org $(System.TeamFoundationCollectionUri) 
  #                         --project $(PROJECT-NAME)                       
  #   displayName: 'Create Pipeline from YAML'